services:
  database:
    container_name: "tabnews_db"
    restart: always
    image: "postgres:16.0-alpine3.18"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "local-password"
