services:
  database:
    container_name: "tabnews_db"
    restart: always
    image: "postgres:16.0-alpine3.18"
    env_file: "../.env.development"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 5
